### ISSUE TITLE
add the full painted check

### ISSUE THREAD

**Issue by Phignis** [Phignis/quest-painting#4]
basic implementation of painting is now live!
now, make a shader and a system to check if the object painted is completed.
Refer to [the file explaining the paint method](https://github.com/Phignis/quest-painting/blob/main/doc/painting_method.md) for more precision about implementation

**Comment by omega2028** [comment]
Aller hop, au boulot ! x)

**Comment by Phignis** [comment]
painting method is using observer design pattern, in order to notify as much object as necessary when object is fully painted
